package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"sct-backend-service/graph/generated"
	"sct-backend-service/graph/model"
	"sct-backend-service/internal/middleware"
)

// SendContactInfo is the resolver for the sendContactInfo field.
func (r *mutationResolver) SendContactInfo(ctx context.Context, input model.SendContactInfoRequest) (*model.SendContactInfoResponse, error) {
	// Update context (add tracing, user info, etc.)
	ctx = middleware.UpdateContext(ctx)
	return r.Workflow.SendContactInfo(ctx, input)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
